import React from "react";
import Person from "./mappingPractice3";

class mapingPractice extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      peopleList: [
        {
          id: 1,
          first_name: "Lorinda",
          last_name: "Chedgey",
          email: "lchedgey0@npr.org",
          spiritAnimal: "Eagle, crowned",
          ip_address: "90.6.104.170",
        },
        {
          id: 2,
          first_name: "Wadsworth",
          last_name: "Simmgen",
          email: "wsimmgen1@github.com",
          spiritAnimal: "Feathertail glider",
          ip_address: "94.169.77.50",
        },
        {
          id: 3,
          first_name: "Sula",
          last_name: "Jarman",
          email: "sjarman2@cyberchimps.com",
          spiritAnimal: "Currasow (unidentified)",
          ip_address: "44.207.235.154",
        },
        {
          id: 4,
          first_name: "Gretta",
          last_name: "Lemery",
          email: "glemery3@accuweather.com",
          spiritAnimal: "Lemming, arctic",
          ip_address: "62.190.9.167",
        },
        {
          id: 5,
          first_name: "Lothaire",
          last_name: "Juszczyk",
          email: "ljuszczyk4@xinhuanet.com",
          spiritAnimal: "Gull, lava",
          ip_address: "118.35.40.104",
        },
        {
          id: 6,
          first_name: "Jock",
          last_name: "Ebbins",
          email: "jebbins5@utexas.edu",
          spiritAnimal: "Spurfowl, yellow-necked",
          ip_address: "242.79.109.22",
        },
        {
          id: 7,
          first_name: "Emiline",
          last_name: "Jessel",
          email: "ejessel6@shop-pro.jp",
          spiritAnimal: "Jungle cat",
          ip_address: "52.232.145.58",
        },
        {
          id: 8,
          first_name: "Genia",
          last_name: "Vaugham",
          email: "gvaugham7@ycombinator.com",
          spiritAnimal: "Spectacled caiman",
          ip_address: "176.114.127.90",
        },
        {
          id: 9,
          first_name: "Mercy",
          last_name: "Keunemann",
          email: "mkeunemann8@sciencedirect.com",
          spiritAnimal: "Black-tailed prairie dog",
          ip_address: "215.210.52.249",
        },
        {
          id: 10,
          first_name: "Friedrich",
          last_name: "Kabsch",
          email: "fkabsch9@geocities.com",
          spiritAnimal: "Secretary bird",
          ip_address: "250.219.6.204",
        },
        {
          id: 11,
          first_name: "Maurizio",
          last_name: "Crocombe",
          email: "mcrocombea@reddit.com",
          spiritAnimal: "Albatross, waved",
          ip_address: "82.111.50.21",
        },
        {
          id: 12,
          first_name: "Kathrine",
          last_name: "Daniau",
          email: "kdaniaub@linkedin.com",
          spiritAnimal: "African bush squirrel",
          ip_address: "85.38.248.198",
        },
        {
          id: 13,
          first_name: "Dall",
          last_name: "Paquet",
          email: "dpaquetc@opera.com",
          spiritAnimal: "Deer, red",
          ip_address: "70.109.96.97",
        },
        {
          id: 14,
          first_name: "Marijo",
          last_name: "Grunson",
          email: "mgrunsond@sitemeter.com",
          spiritAnimal: "Royal tern",
          ip_address: "55.91.240.8",
        },
        {
          id: 15,
          first_name: "Julieta",
          last_name: "Gadesby",
          email: "jgadesbye@phpbb.com",
          spiritAnimal: "Cat, toddy",
          ip_address: "163.58.110.78",
        },
        {
          id: 16,
          first_name: "Hartwell",
          last_name: "Meffen",
          email: "hmeffenf@imageshack.us",
          spiritAnimal: "Canada goose",
          ip_address: "205.73.243.37",
        },
        {
          id: 17,
          first_name: "Coleman",
          last_name: "Lyffe",
          email: "clyffeg@reverbnation.com",
          spiritAnimal: "Galapagos penguin",
          ip_address: "37.69.189.23",
        },
        {
          id: 18,
          first_name: "Lilian",
          last_name: "Khidr",
          email: "lkhidrh@constantcontact.com",
          spiritAnimal: "Robin, white-throated",
          ip_address: "128.218.226.159",
        },
        {
          id: 19,
          first_name: "Hyatt",
          last_name: "Reddell",
          email: "hreddelli@samsung.com",
          spiritAnimal: "Armadillo, nine-banded",
          ip_address: "197.148.87.142",
        },
        {
          id: 20,
          first_name: "Elena",
          last_name: "Vamplus",
          email: "evamplusj@arstechnica.com",
          spiritAnimal: "African jacana",
          ip_address: "148.179.249.243",
        },
        {
          id: 21,
          first_name: "Una",
          last_name: "Jellicorse",
          email: "ujellicorsek@hud.gov",
          spiritAnimal: "Lesser flamingo",
          ip_address: "3.66.249.138",
        },
        {
          id: 22,
          first_name: "Ashien",
          last_name: "Reely",
          email: "areelyl@nih.gov",
          spiritAnimal: "Antelope ground squirrel",
          ip_address: "176.217.29.94",
        },
        {
          id: 23,
          first_name: "Zacharie",
          last_name: "Cloake",
          email: "zcloakem@wsj.com",
          spiritAnimal: "Gull, lava",
          ip_address: "63.56.226.242",
        },
        {
          id: 24,
          first_name: "Daryle",
          last_name: "Embury",
          email: "demburyn@bluehost.com",
          spiritAnimal: "Coyote",
          ip_address: "218.117.0.219",
        },
        {
          id: 25,
          first_name: "Murdoch",
          last_name: "Bibey",
          email: "mbibeyo@buzzfeed.com",
          spiritAnimal: "Cat, jungle",
          ip_address: "251.131.250.18",
        },
        {
          id: 26,
          first_name: "Lorant",
          last_name: "Pointer",
          email: "lpointerp@yandex.ru",
          spiritAnimal: "Gecko, barking",
          ip_address: "17.187.88.103",
        },
        {
          id: 27,
          first_name: "Matias",
          last_name: "McBrearty",
          email: "mmcbreartyq@plala.or.jp",
          spiritAnimal: "Waterbuck, defassa",
          ip_address: "185.240.88.151",
        },
        {
          id: 28,
          first_name: "Dominick",
          last_name: "Durbyn",
          email: "ddurbynr@usa.gov",
          spiritAnimal: "Bat, little brown",
          ip_address: "136.115.136.219",
        },
        {
          id: 29,
          first_name: "Kareem",
          last_name: "Warsap",
          email: "kwarsaps@google.nl",
          spiritAnimal: "Monkey, rhesus",
          ip_address: "27.33.107.174",
        },
        {
          id: 30,
          first_name: "Salem",
          last_name: "Broadis",
          email: "sbroadist@discovery.com",
          spiritAnimal: "Flamingo, roseat",
          ip_address: "106.105.55.162",
        },
        {
          id: 31,
          first_name: "Nickey",
          last_name: "Yankishin",
          email: "nyankishinu@bizjournals.com",
          spiritAnimal: "Boubou, southern",
          ip_address: "45.243.72.173",
        },
        {
          id: 32,
          first_name: "Carr",
          last_name: "McShea",
          email: "cmcsheav@bing.com",
          spiritAnimal: "Hottentot teal",
          ip_address: "35.183.244.15",
        },
        {
          id: 33,
          first_name: "Chev",
          last_name: "Moresby",
          email: "cmoresbyw@timesonline.co.uk",
          spiritAnimal: "Tenrec, tailless",
          ip_address: "153.123.143.48",
        },
        {
          id: 34,
          first_name: "Barbi",
          last_name: "Ricker",
          email: "brickerx@booking.com",
          spiritAnimal: "White rhinoceros",
          ip_address: "65.168.103.108",
        },
        {
          id: 35,
          first_name: "Norby",
          last_name: "Podd",
          email: "npoddy@usa.gov",
          spiritAnimal: "Egyptian vulture",
          ip_address: "49.136.97.238",
        },
        {
          id: 36,
          first_name: "Natalya",
          last_name: "Francie",
          email: "nfranciez@gravatar.com",
          spiritAnimal: "Killer whale",
          ip_address: "115.192.55.216",
        },
        {
          id: 37,
          first_name: "Luigi",
          last_name: "Spowart",
          email: "lspowart10@naver.com",
          spiritAnimal: "Wolf spider",
          ip_address: "6.23.71.72",
        },
        {
          id: 38,
          first_name: "Emmett",
          last_name: "Poge",
          email: "epoge11@reuters.com",
          spiritAnimal: "Musk ox",
          ip_address: "19.81.222.214",
        },
        {
          id: 39,
          first_name: "Lodovico",
          last_name: "Ellesworth",
          email: "lellesworth12@vimeo.com",
          spiritAnimal: "Blue-breasted cordon bleu",
          ip_address: "250.134.243.10",
        },
        {
          id: 40,
          first_name: "Staci",
          last_name: "McClunaghan",
          email: "smcclunaghan13@techcrunch.com",
          spiritAnimal: "Crab, red lava",
          ip_address: "65.186.73.242",
        },
        {
          id: 41,
          first_name: "Evangelin",
          last_name: "Withrington",
          email: "ewithrington14@mapy.cz",
          spiritAnimal: "Collared peccary",
          ip_address: "93.20.134.153",
        },
        {
          id: 42,
          first_name: "Ram",
          last_name: "Lutwidge",
          email: "rlutwidge15@zimbio.com",
          spiritAnimal: "American beaver",
          ip_address: "45.4.62.177",
        },
        {
          id: 43,
          first_name: "Darren",
          last_name: "Phelipeaux",
          email: "dphelipeaux16@360.cn",
          spiritAnimal: "Duck, comb",
          ip_address: "79.158.57.172",
        },
        {
          id: 44,
          first_name: "Giorgi",
          last_name: "Le Fevre",
          email: "glefevre17@ucsd.edu",
          spiritAnimal: "Nine-banded armadillo",
          ip_address: "89.180.236.194",
        },
        {
          id: 45,
          first_name: "Terri",
          last_name: "Ellerton",
          email: "tellerton18@ucla.edu",
          spiritAnimal: "Barbet, levaillant's",
          ip_address: "8.144.80.119",
        },
        {
          id: 46,
          first_name: "Gertrud",
          last_name: "Burghill",
          email: "gburghill19@mapquest.com",
          spiritAnimal: "Vulture, oriental white-backed",
          ip_address: "206.15.208.252",
        },
        {
          id: 47,
          first_name: "Kara-lynn",
          last_name: "Vile",
          email: "kvile1a@joomla.org",
          spiritAnimal: "Black kite",
          ip_address: "67.64.75.67",
        },
        {
          id: 48,
          first_name: "Gertie",
          last_name: "Althorp",
          email: "galthorp1b@taobao.com",
          spiritAnimal: "Lesser mouse lemur",
          ip_address: "124.192.122.184",
        },
        {
          id: 49,
          first_name: "Alethea",
          last_name: "Ingerman",
          email: "aingerman1c@etsy.com",
          spiritAnimal: "Little brown bat",
          ip_address: "188.64.118.6",
        },
        {
          id: 50,
          first_name: "Hansiain",
          last_name: "Stefanovic",
          email: "hstefanovic1d@tamu.edu",
          spiritAnimal: "Gecko (unidentified)",
          ip_address: "29.21.151.212",
        },
      ],
    };
  }

  mapPerson = (onePerson) => {
    return (
      <Person avenger={onePerson}></Person>
      // <h5>
      //   {onePerson.name}
      //   {"   "}
      //   {onePerson.id}
      // </h5>
    );
  };

  render() {
    return (
      <div className="row">{this.state.peopleList.map(this.mapPerson)}</div>
    );
  }
}

export default mapingPractice;
